language: python
python: 3.5.1
install: pip install -r requirement.txt
script: python hello-world.py
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
